[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "pulse_amplitude"
features = ["participant", "compound_position", "compound_size"]
response = ["LADM", "LBiceps", "LDeltoid", "LECR", "LFCR", "LTriceps"]

[mcmc]
num_chains = 4
num_warmup = 5000
num_samples = 1000
thinning = 1

[optional]
mep_matrix_path = "/home/vishu/data/hbmep-processed/C_SMA_LAR/mat.npy"
mep_response = ['LADM', 'LBiceps', 'LBicepsFemoris', 'LDeltoid', 'LECR', 'LFCR', 'LTriceps', 'RBiceps']
mep_window = [-0.01, 0.025]
mep_size_window = [0.0015, 0.01]

[misc]
base = 20
